Installation Page
ChhikaraBRUH/SNKRS-UI pull request #11
Opened 2022-02-07 17:57 UTC by ChhikaraBRUH

Added Installation Page

2022-02-08 17:13 UTC, Tejinder15 requested changes
![image](https://user-images.githubusercontent.com/63464204/153039460-6e51b170-aee9-4874-a205-324a8b7404fa.png)

The Site isn't Responsive and also try to give proper spacing in para lines

2022-02-08 18:02 UTC, mohammed-sas approved these changes

2022-02-09 17:43 UTC, ChhikaraBRUH commented
> ![image](https://user-images.githubusercontent.com/63464204/153039460-6e51b170-aee9-4874-a205-324a8b7404fa.png)
> 
> The Site isn't Responsive and also try to give proper spacing in para lines

I have added general responsiveness to the docs page as well as all the other pages @Tejinder15

2022-02-09 17:52 UTC, mohammed-sas approved these changes

2022-02-09 18:07 UTC, RahullRawat approved these changes

2022-02-09 18:07 UTC, AnkurChunekar approved these changes

2022-02-09 18:14 UTC, merged